eureka:
  client:
    service-url:
      defaultZone: http://121.40.213.185:9500/eureka/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${eureka.instance.non-secure-port}
    ip-address: 122.51.89.208
    non-secure-port: 9516
spring:
  datasource:
#    hikari:
#      username:
#      password:
#      jdbc-url:
#      driver-class-name:
#      maximum-pool-size:
#      max-lifetime:
    jdbc-url: jdbc:mysql://121.40.213.185:3306/managedb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ONEC2112e
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    useSSL: false
    maximun-pool-size: 100
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
  redis:
    password: onec2112
    #    cluster:
    #      nodes: 127.0.0.1:6379
    #      max-redirects:
    jedis:
      pool:
        max-active: 500
        max-idle: 8
        max-wait: 12
    timeout: 5000
    host: 121.40.213.185
    port: 6379
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    suffix: .html
ribbon:
  ReadTimeout: 70000
  ConnectTimeout: 10000
checkExampleEntityClass: true
enableMethodAnnotation: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000