eureka:
  client:
    service-url:
      defaultZone: http://121.40.213.185:9500/eureka/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${eureka.instance.non-secure-port}
    ip-address: 122.51.89.208
    non-secure-port: 9514
spring:
  datasource:
    master:
      jdbcUrl: jdbc:mysql://121.40.213.185:3306/productdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: ONEC2112e
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      useSSL: false
      maximun-pool-size: 100
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    middle:
      jdbcUrl: jdbc:mysql://121.40.213.185:3306/productdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: ONEC2112e
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      useSSL: false
      maximun-pool-size: 100
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  redis:
    password: onec2112
    #    cluster:
    #      nodes: 127.0.0.1:6379
    #      max-redirects:
    jedis:
      pool:
        max-active: 500
        max-idle: 8
        max-wait: 12
    timeout: 5000
    host: 121.40.213.185
    port: 6379
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 10000
  checkExampleEntityClass: true
  enableMethodAnnotation: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000