logging:
  config: classpath:log4j2_manage.yml

server:
  port: 9520

  undertow:
    io-threads: 4
    worker-threads: 32
    buffer-size: 1024
    direct-buffers: true
    servlet:
      context-path: /notify

# 注册到服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9500/eureka/
spring:
  application:
    name: notify
  profiles:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/notifydb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: ONEC
      password: 2112
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      useSSL: false
      maximun-pool-size: 100
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/onlinedb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: ONEC
      password: 2112
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      useSSL: false
      maximun-pool-size: 100
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.MySQL57Dialect
  redis:
    password: 2112
    cluster:
      nodes: 127.0.0.1:7963
      max-redirects:
    jedis:
      pool:
        max-active: 500
        max-idle: 8
        max-wait: 12s
    timeout: 12s
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java/com
  mail:
    host: smtp.qq.com
    username: 2650020302@qq.com
    password: ijfebctnfnabebac # QQ 邮箱授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  # 设置默认密码：
  security:
    user:
      name: user
      password: 22222

# 配置rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-returns: false
    publisher-confirms: false

